name: postprocess-workflow-test

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]
  repository_dispatch:
    types: [opened, deleted, custom]

env:
  CARGO_TERM_COLOR: always

jobs:
  postprocess:
    runs-on: [self-hosted, Linux, X64]
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - name: Call postprocess
      run:  echo "I would ./postprocess.sh"

